version: 2
jobs:
  build:
    docker:
      - image: cypress/browsers:chrome64

    working_directory: ~/app

    steps:
      - checkout

      - run: node --version && npm --version && npx --version && yarn --version

      - add-ssh-keys:
          fingerprints:
            - "e1:ca:5d:f0:58:11:c7:ae:b7:ac:4a:1b:cc:3a:0d:4a"

      - restore_cache:
          keys:
            - v4-dependencies-{{ checksum "yarn.lock" }}
            - v4-dependencies-

      - run: yarn install

      - run: yarn build

      - run: 
          command: yarn start
          background: true

      - run: npx wait-on http://localhost:3000

      - run: yarn test

      - store_test_results:
          path: junit

      - store_artifacts:
          path: cypress/screenshots

      - save_cache:
          paths:
            - node_modules
          key: v4-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn semantic-release || true

      - run:
          name: Maybe deploy to gh-pages
          command: |
            if [[ $CIRCLE_BRANCH == master ]]; then
              yarn docs
            fi